title: <p align="center"> Kundan Tripathi </p>
logo: /assets/img/DP_Dec2019.jpg
description: I am an Analytics professional with a keen interest in Data Science and Artificial Intelligence. 
theme: jekyll-theme-minimal
