title: <p align="center"> Kundan Tripathi </p>
logo: /assets/img/DP_Dec2019.png
description: I am an Analytics professional with a keen interest in Data Science and Artificial Intelligence. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
